# Display.
title: "Merely Useful"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/merely-useful/merely-useful.github.io/"
email: "gvwilson@third-bit.com"
isbn: "000-0-0000000-0-0"
website: "http://merely-useful.github.io/"
purchase: ""
paypal: ""

# Theme color.
background: "#fafafa"

# Jekyll settings.
highlighter: rouge
plugins:
  - "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- tex_en

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    keypoints: "Key points"
    objectives: "After reading this chapter, you will be able to..."
    questions: "Questions this lesson answers"
    singlepage: "Single page version"
