# Display.
title: "Youbou Template"
subtitle: "A template for building lessons with Jekyll and LaTeX"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/youbou/"
email: "gvwilson@third-bit.com"
isbn: "000-0-0000000-0-0"
website: "http://gvwilson.github.io/youbou/"
purchase: ""
paypal: ""

# Theme color.
background: "#f0e0e0"

# Jekyll settings.
highlighter: rouge
plugins:
  - "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- tex_um

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_um:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_um
    values:
      language: "um"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /gloss/

# Translations by language.
translations:
  um:
    donate: "Cursus risus at ultrices, mi tempus imperdiet nulla malesuada pellentesque <a href='^1'>$10</a> (amet tellus cras). Dis parturient montes nascetur ridiculus mus mauris."
    generated: "Lastum generatum"
    lulu: "Purchasum ad Lulu."
    objectives: "Sodales ut etiam sit amet nisl purus in..."
    singlepage: "Single page version"
